name: Build CV

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t resume-builder .

      - name: Run container
        run: docker run --name resume-container resume-builder

      - name: Copy PDF
        run: docker cp resume-container:/resume/CV/main.pdf ./main.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: main.pdf
